name: tests
on: [push]
jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install lisp  
        run: |
          cd ${{ github.workspace }}; \
          git clone git://git.code.sf.net/p/sbcl/sbcl; \
          cd sbcl; sh run-sbcl.sh; \
          ls; ls bin
      - name: Run tests  
        run: |
          cd ${{ github.workspace }}/src; pwd; ls ..; \
          ls;
      - run: echo "ğŸ This job's status is ${{ job.status }}."
